version: '3'
services:

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    platform: linux/amd64
    ports:
      - '80:3000'
      - '3030:3030'
      - '3003:3003'
    depends_on:
      - mongo
      - minio
    environment:
      HMR_PORT: 3003
      PORT: 3000
      ROOT_URL: http://localhost
      VUE_DEV_SERVER_URL: http://localhost:3003
      MONGO_URL: mongodb://mongo:27017/meteor
      MAIL_URL: smtp://maildev:25
      NODE_TLS_REJECT_UNAUTHORIZED: 0
    volumes:
      - ./:/latelier
      - /latelier/.cache
      - /latelier/.meteor/local
      - /latelier/node_modules
      - attachments:/attachments
    networks:
      - latelier-network

  mongo:
    image: mongo:latest
    command:
      - --storageEngine=wiredTiger
      - --logpath=/dev/null
    volumes:
      - data:/data/db
    networks:
      - latelier-network

  mongoexpress:
    image: mongo-express
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
    ports:
      - "8081:8081"
    networks:
      - latelier-network
  
  maildev:
    image: djfarrelly/maildev
    ports:
      - "1080:80"
      - "1025:25"
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      - minio-data:/data
    command: ["server", "--console-address", ":9001", "/data"]
    networks:
      - latelier-network

  minio_mc:
    image: minio/mc:latest
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      mc alias set minio http://minio:9000 minio minio123;
      "      
    networks:
      - latelier-network


networks:
  latelier-network:
volumes:
  data:
  attachments:
  minio-data:
